///--- MANTENIMIENTO REMINDER ---/
export const GET_REMINDERS = 'GET_REMINDERS'
export const GET_REMINDERS_SUCCESS ='GET_REMINDERS_SUCCESS'
export const GET_REMINDERS_ERROR ='GET_REMINDERS_ERROR'


export const SAVE_REMINDER = 'SAVE_REMINDER'
export const SAVE_REMINDER_SUCCESS ='SAVE_REMINDER_SUCCESS'
export const SAVE_REMINDER_ERROR ='SAVE_REMINDER_ERROR'


export const DELETE_REMINDER = 'DELETE_REMINDER'
export const DELETE_REMINDER_SUCCESS ='DELETE_REMINDER_SUCCESS'
export const DELETE_REMINDER_ERROR ='DELETE_REMINDER_ERROR'


export const DELETE_REMINDER_LIST = 'DELETE_REMINDER_LIST'
export const DELETE_REMINDER_LIST_SUCCESS ='DELETE_REMINDER_LIST_SUCCESS'
export const DELETE_REMINDER_LIST_ERROR ='DELETE_REMINDER_LIST_ERROR'

/// FEEDBACK
export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const  CLOSE_FEEDBACK = 'CLOSE_FEEDBACK';

