///--- MANTENIMIENTO REMINDER ---/
export const GET_REMINDERS = 'GET_REMINDERS'
export const GET_REMINDERS_SUCCESS ='GET_REMINDERS_SUCCESS'
export const GET_REMINDERS_ERROR ='GET_REMINDERS_ERROR'


export const SAVE_REMINDER = 'SAVE_REMINDER'
export const SAVE_REMINDER_SUCCESS ='SAVE_REMINDER_SUCCESS'
export const SAVE_REMINDER_ERROR ='SAVE_REMINDER_ERROR'

/// FEEDBACK
export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const  CLOSE_FEEDBACK = 'CLOSE_FEEDBACK';

